/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 17-ene.-2022 1:27:21 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */


USE `cofftea`;


SET FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS `category_product` CASCADE
;

DROP TABLE IF EXISTS `invoice_detail` CASCADE
;

DROP TABLE IF EXISTS `products` CASCADE
;

DROP TABLE IF EXISTS `profile` CASCADE
;

DROP TABLE IF EXISTS `sales_invoice` CASCADE
;

DROP TABLE IF EXISTS `type_product` CASCADE
;

DROP TABLE IF EXISTS `users` CASCADE
;

/* Create Tables */

CREATE TABLE `category_product`
(
	`id_category_product` INT NOT NULL auto_increment,
	`description` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_category` PRIMARY KEY (`id_category_product` ASC)
)

;

CREATE TABLE `invoice_detail`
(
	`id_invoice_detail` INT NOT NULL auto_increment,
	`id_sales_invoice` INT NOT NULL,
	`id_products` INT NULL,
	`quantity` DOUBLE(10,2) NOT NULL,
	`unit_price` DOUBLE(10,2) NOT NULL,
	`discount` DOUBLE(10,2) NULL,
	`subtotal` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_invoice_detail` PRIMARY KEY (`id_invoice_detail` ASC)
)

;

CREATE TABLE `products`
(
	`id_products` INT NOT NULL auto_increment,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(200) NOT NULL,
	`price` DOUBLE(10,2) NOT NULL,
	`discount` DOUBLE(4,2) NOT NULL,
	`id_category_product` INT NULL,
	`id_type_product` INT NULL,
	`image` VARCHAR(300) NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_products` ASC)
)

;

CREATE TABLE `profile`
(
	`id_profile` INT NOT NULL auto_increment,
	`description` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_profile` PRIMARY KEY (`id_profile` ASC)
)

;

CREATE TABLE `sales_invoice`
(
	`id_sales_invoice` INT NOT NULL auto_increment,
	`id_users` INT NOT NULL,
	`date_registration` DATE NOT NULL,
	`subtotal` DOUBLE(10,2) NOT NULL,
	`tax` DOUBLE(10,2) NOT NULL,
	`total_cost` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_sales_invoice` PRIMARY KEY (`id_sales_invoice` ASC)
)

;

CREATE TABLE `type_product`
(
	`id_type_product` INT NOT NULL auto_increment,
	`description` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_type` PRIMARY KEY (`id_type_product` ASC)
)

;

CREATE TABLE `users`
(
	`id_users` INT NOT NULL auto_increment,
	`first_name` VARCHAR(150) NOT NULL,
	`last_name` VARCHAR(150) NOT NULL,
	`email` VARCHAR(100) NOT NULL,
	`password` VARCHAR(300) NOT NULL,
	`second_password` VARCHAR(300) NOT NULL,
	`province` VARCHAR(100) NULL,
	`location` VARCHAR(100) NULL,
	`street` VARCHAR(100) NULL,
	`avatar` VARCHAR(200) NOT NULL,
	`id_profile` INT NOT NULL,
	CONSTRAINT `PK_users` PRIMARY KEY (`id_users` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `invoice_detail` 
 ADD INDEX `IXFK_invoice_detail_products` (`id_products` ASC)
;

ALTER TABLE `invoice_detail` 
 ADD INDEX `IXFK_invoice_detail_sales_invoice` (`id_sales_invoice` ASC)
;

ALTER TABLE `products` 
 ADD INDEX `IXFK_products_category_product` (`id_category_product` ASC)
;

ALTER TABLE `products` 
 ADD INDEX `IXFK_products_type_product` (`id_type_product` ASC)
;

ALTER TABLE `sales_invoice` 
 ADD INDEX `IXFK_sales_invoice_users` (`id_users` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IXFK_users_profile` (`id_profile` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `invoice_detail` 
 ADD CONSTRAINT `FK_invoice_detail_products`
	FOREIGN KEY (`id_products`) REFERENCES `products` (`id_products`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `invoice_detail` 
 ADD CONSTRAINT `FK_invoice_detail_sales_invoice`
	FOREIGN KEY (`id_sales_invoice`) REFERENCES `sales_invoice` (`id_sales_invoice`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `products` 
 ADD CONSTRAINT `FK_products_category_product`
	FOREIGN KEY (`id_category_product`) REFERENCES `category_product` (`id_category_product`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `products` 
 ADD CONSTRAINT `FK_products_type_product`
	FOREIGN KEY (`id_type_product`) REFERENCES `type_product` (`id_type_product`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `sales_invoice` 
 ADD CONSTRAINT `FK_sales_invoice_users`
	FOREIGN KEY (`id_users`) REFERENCES `users` (`id_users`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `users` 
 ADD CONSTRAINT `FK_users_profile`
	FOREIGN KEY (`id_profile`) REFERENCES `profile` (`id_profile`) ON DELETE Restrict ON UPDATE Restrict
;


SET FOREIGN_KEY_CHECKS=1 
;
