/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 17-ene.-2022 9:09:29 a. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `users` CASCADE
;

/* Create Tables */

CREATE TABLE `users`
(
	`id_users` INT NOT NULL DEFAULT auto_increment,
	CONSTRAINT `PK_users` PRIMARY KEY (`id_users` ASC)
)

;

SET FOREIGN_KEY_CHECKS=1 
;
